### ISSUE TITLE
Newest rerolled tarball not works 1.13.0.3

### ISSUE THREAD

**Issue by nemysis** [habnabit/txsocksx#12]
I have make RPM for openSUSE and have worked old tarball 1.13.0.3

https://build.opensuse.org/package/show/network/python-txsocksx

```\n
[   41s] vcversioner: no VCS could be detected in u'/home/abuild/rpmbuild/BUILD/txsocksx-1.13.0.3' and u'/home/abuild/rpmbuild/BUILD/txsocksx-1.13.0.3/version.txt' isn't present.
[   41s] vcversioner: are you installing from a github tarball?
[   41s] error: Bad exit status from /var/tmp/rpm-tmp.8IjsMW (%build)
```

Please use old tarball in

https://github.com/habnabit/txsocksx/releases

**Comment by habnabit** [comment]
Releases are [on pypi](https://pypi.python.org/pypi/txsocksx), not [on github](https://github.com/habnabit/txsocksx/releases). I can see if I can make github point to pypi, though. The tarballs which are uploaded to pypi have extra version metadata that github tarballs do not. I think switching to [versioneer](https://github.com/warner/python-versioneer) will fix that, but I don't know if it contains everything I need yet.

**Comment by nemysis** [comment]
Yes look this I use PyPy

https://build.opensuse.org/package/show/network/python-txsocksx

**Comment by habnabit** [comment]
I just released [1.15.0.2](https://pypi.python.org/pypi/txsocksx/1.15.0.2); can you try with that?

**Comment by nemysis** [comment]
I try this but not see changes
- Update to 1.15.0.2, no changelog entry

**Comment by nemysis** [comment]
Just have commited to my home

https://build.opensuse.org/package/show/home:nemysis:branches:network/python-txsocksx

and make request

https://build.opensuse.org/request/show/320276
