### ISSUE TITLE
_SOCKAgent's _getEndpoint request doesn't work with Twisted >= 15.0

### ISSUE THREAD

**Issue by nihilifer** [habnabit/txsocksx#13]
During call of _SOCKAgent's *request* method, the following traceback appears:

```
File "/usr/lib64/python2.7/site-packages/twisted/web/client.py", line 1926, in request
    deferred = self._agent.request(method, uri, headers, bodyProducer)
  File "/usr/lib64/python2.7/site-packages/twisted/web/client.py", line 1559, in request
    endpoint = self._getEndpoint(parsedURI)
TypeError: _getEndpoint() takes exactly 4 arguments (2 given)
```

That's because Twisted >= 15.0 changed signature of _getEndpoint method.

**Comment by habnabit** [comment]
Sorry, but is this not fixed in the current `HEAD@master` (f5fb3c6aba71127fccd1eacdae6a764b775c22e2) ? See: https://travis-ci.org/habnabit/txsocksx/builds/66601869

**Comment by hellais** [comment]
I can confirm this is fixed, but could you please tag a new release?

There is also an open bug on the debian tracker: https://bugs.debian.org/794369

**Comment by habnabit** [comment]
Try again with the new [1.15.0.2](https://pypi.python.org/pypi/txsocksx/1.15.0.2) release and see if that fixes your issue.

**Comment by nhlfr** [comment]
Version 1.15.0.2 fixes my issue. Thank you very much!
