### ISSUE TITLE
txsocksx breaks with twisted 15.0.0

### ISSUE THREAD

**Issue by hellais** [habnabit/txsocksx#9]
In twisted 15.0.0 the signature of of the `_getEndpoint`  method of agent has changed to accept only 1 argument: https://github.com/twisted/twisted/blob/trunk/twisted/web/client.py#L1535. This means that the `SOCKSAgent` will no longer work with twisted 15.0.0: https://github.com/habnabit/txsocksx/blob/master/txsocksx/http.py#L28.

The quick fix to this would be to make the arguments of `_getEndpoint` optional and depending on the number of arguments passed (2 vs 4) treat the second argument as either a `uri` or a `scheme`, though perhaps there is a smarter way of doing this.

It's quite important that we get a fix for this released soonish since software that depends on txsocksx and uses it's SOCKSAgent is currently broken with the latest twisted.

**Comment by tomprince** [comment]
The correct fix is to make the agents use `twisted.web.client.Agent.usingEndpointFactory` instead of overriding a private function. That constructor was added to support this use case.

**Comment by hellais** [comment]
@habnabit any updates on this? Should I make a pull request using the suggestion of @tomprince?

**Comment by meejah** [comment]
@hellais yes, please! I will take a stab if you're not planning on working on this in the next week or so...

**Comment by habnabit** [comment]
in progress; see 5e3d006c45072da13b9bd0277ba111f9d0572031.

**Comment by hellais** [comment]
Could you perhaps also make a new release that include this fix?
